/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/series": {
    /**
     * List all series
     * @description Returns a list of all available series of The Traitors UK.
     */
    get: operations["listSeries"];
  };
  "/series/{seriesId}": {
    /**
     * Get a specific series
     * @description Returns detailed information for a single series.
     */
    get: operations["getSeriesById"];
  };
  "/series/{seriesId}/candidates": {
    /**
     * Get candidates for a series
     * @description Returns a list of all candidates who participated in a specific series.
     */
    get: operations["getCandidatesBySeries"];
  };
  "/series/{seriesId}/votes": {
    /**
     * Get votes for a series
     * @description Returns a list of all votes cast in a specific series.
     */
    get: operations["getVotesBySeries"];
  };
  "/candidates/{candidateId}": {
    /**
     * Get a specific candidate
     * @description Returns detailed information for a single candidate.
     */
    get: operations["getCandidateById"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Series: {
      /**
       * @description The unique identifier for the series.
       * @example 1
       */
      id: number;
      /**
       * @description The year the series was broadcast.
       * @example 2022
       */
      year: number;
      /**
       * @description The full title of the series.
       * @example The Traitors (UK series 1)
       */
      title: string;
    };
    Candidate: {
      /**
       * @description The unique identifier for the candidate.
       * @example 101
       */
      id: number;
      /**
       * @description The name of the candidate.
       * @example Alyssa
       */
      name: string;
      /**
       * @description The ID of the series the candidate participated in.
       * @example 1
       */
      seriesId: number;
      /**
       * @description The candidate's role in the game.
       * @enum {string}
       */
      role: "Faithful" | "Traitor";
      /**
       * @description The final outcome for the candidate.
       * @example Murdered
       */
      outcome: string;
    };
    Vote: {
      /** @description The unique identifier for the vote event. */
      id: number;
      /** @description The episode number in which the vote occurred. */
      episode: number;
      /** @description The ID of the candidate who cast the vote. */
      voterId: number;
      /** @description The ID of the candidate who received the vote. */
      votedForId: number;
      /** @description The ID of the series this vote belongs to. */
      seriesId: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * List all series
   * @description Returns a list of all available series of The Traitors UK.
   */
  listSeries: {
    responses: {
      /** @description A successful response with an array of series. */
      200: {
        content: {
          "application/json": components["schemas"]["Series"][];
        };
      };
    };
  };
  /**
   * Get a specific series
   * @description Returns detailed information for a single series.
   */
  getSeriesById: {
    parameters: {
      path: {
        seriesId: number;
      };
    };
    responses: {
      /** @description A successful response with the series data. */
      200: {
        content: {
          "application/json": components["schemas"]["Series"];
        };
      };
      /** @description Series not found. */
      404: {
        content: never;
      };
    };
  };
  /**
   * Get candidates for a series
   * @description Returns a list of all candidates who participated in a specific series.
   */
  getCandidatesBySeries: {
    parameters: {
      query?: {
        /** @description The maximum number of candidates to return. */
        limit?: number;
        /** @description The number of candidates to skip before starting to collect the result set. */
        offset?: number;
        /** @description The field to sort by. */
        sortBy?: "name";
        /** @description The order to sort by. */
        sortOrder?: "asc" | "desc";
      };
      path: {
        seriesId: number;
      };
    };
    responses: {
      /** @description A successful response with an array of candidates. */
      200: {
        content: {
          "application/json": components["schemas"]["Candidate"][];
        };
      };
      /** @description Series not found. */
      404: {
        content: never;
      };
    };
  };
  /**
   * Get votes for a series
   * @description Returns a list of all votes cast in a specific series.
   */
  getVotesBySeries: {
    parameters: {
      query?: {
        /** @description The maximum number of votes to return. */
        limit?: number;
        /** @description The number of votes to skip before starting to collect the result set. */
        offset?: number;
      };
      path: {
        seriesId: number;
      };
    };
    responses: {
      /** @description A successful response with an array of votes. */
      200: {
        content: {
          "application/json": components["schemas"]["Vote"][];
        };
      };
      /** @description Series not found. */
      404: {
        content: never;
      };
    };
  };
  /**
   * Get a specific candidate
   * @description Returns detailed information for a single candidate.
   */
  getCandidateById: {
    parameters: {
      path: {
        candidateId: number;
      };
    };
    responses: {
      /** @description A successful response with the candidate data. */
      200: {
        content: {
          "application/json": components["schemas"]["Candidate"];
        };
      };
      /** @description Candidate not found. */
      404: {
        content: never;
      };
    };
  };
}
